name: Deploy alerts
on:
  push:
    branches:
      - main
      - dev
    paths:
      - '.nais/alerts-dev.yaml'
      - '.nais/alerts-prod.yaml'
permissions:
  contents: "write"
  id-token: "write"

jobs:
  deploy-dev:
    name: Deploy alerts to dev
    uses: navikt/mob-gha-workflows/.github/workflows/nais-alert-deploy.yaml@main
    with:
      cluster: dev-fss
      resource: .nais/alerts-dev.yaml

  deploy-alerts-prod:
    name: Deploy alerts to prod
    if: github.ref == 'refs/heads/main'
    uses: navikt/mob-gha-workflows/.github/workflows/nais-alert-deploy.yaml@main
    with:
      cluster: prod-fss
      resource: .nais/alerts-prod.yaml