name: Deploy

on:
  push:
    branches:
      - main
      - dev
      - chore/oppdatere-bygg-til-mob-gha-workflows
    paths-ignore:
      - '**.md'
      - 'LICENCE'
      - 'CODEOWNERS'
      - '.gitignore'
      - 'setupLocalEnvironment.sh'
      - '.github/workflows/build-pr.yaml'
      - '.github/workflows/security.yaml'
      - '.github/workflows/alerts.yaml'
      - '.nais/alerts-dev.yaml'
      - '.nais/alerts-prod.yaml'
      - '.github/dependabot.yaml'
env:
  TZ: Europe/Oslo

permissions:
  contents: "write"
  id-token: "write"

jobs:
  build:
    name: Build/test & push image
    uses: navikt/mob-gha-workflows/.github/workflows/gradle-build-push-image.yaml@main
    secrets: inherit

  deploy-dev:
    needs: build
    name: Deploy to dev-fss
    uses: navikt/mob-gha-workflows/.github/workflows/nais-app-deploy.yaml@main
    with:
      cluster: dev-fss
      resource: .nais/naiserator-q1.yaml
      image: ${{ needs.build.outputs.image }}

  deploy-prod:
    name: Deploy to prod-fss
    needs: [ build , deploy-dev ]
    if: github.ref == 'refs/heads/main'
    uses: navikt/mob-gha-workflows/.github/workflows/nais-app-deploy.yaml@main
    with:
      cluster: prod-fss
      resource: .nais/naiserator-prod.yaml
      image: ${{ needs.build.outputs.image }}