name: Deploy application manually

on:
  workflow_dispatch:

env:
  TZ: Europe/Oslo

permissions:
  contents: "write"
  id-token: "write"

jobs:
  run-application-tests:
    name: Run tests
    uses: navikt/mob-gha-workflows/.github/workflows/gradle-run-test.yaml@new_workflow_release

  assemble-build-push-image-dev:
    needs: [ run-application-tests ]
    name: Assemble application & build/push image dev
    uses: navikt/mob-gha-workflows/.github/workflows/gradle-assemble-build-push-image.yaml@new_workflow_release
    secrets: inherit
    with:
      dockerfile: './.nais/dev/Dockerfile'
      image-tag: 'snapshot'

  deploy-dev:
    needs: [ assemble-build-push-image-dev ]
    name: Deploy to dev-fss
    uses: navikt/mob-gha-workflows/.github/workflows/nais-app-deploy.yaml@main
    with:
      cluster: dev-fss
      resource: .nais/dev/naiserator-dev.yaml
      image: ${{ needs.assemble-build-push-image-dev.outputs.image }}